"""add_read_time_tracking_full

Revision ID: 26e12b8c349a
Revises: 890999486956
Create Date: 2026-04-08 14:13:50.401891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e12b8c349a'
down_revision: Union[str, None] = '890999486956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands manually adjusted for completeness and SQLite compatibility ###
    
    # Create Content Reading Log table
    op.create_table('content_reading_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('content_id', sa.String(length=50), nullable=False),
        sa.Column('total_seconds', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('is_completed', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('last_sync', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_content_reading_logs_user_id', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='pk_content_reading_logs')
    )
    op.create_index('ix_content_reading_logs_user_id', 'content_reading_logs', ['user_id'])
    op.create_index('ix_content_reading_logs_content_id', 'content_reading_logs', ['content_id'])

    with op.batch_alter_table('attendance_protocols', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_reading_seconds', sa.Integer(), nullable=False, server_default='30'))

    with op.batch_alter_table('sops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_reading_seconds', sa.Integer(), nullable=False, server_default='30'))

    # user_onboarding_progress index exists but let's ensure constraints are clean
    # Batch mode handles the table recreation if needed for SQLite.

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sops', schema=None) as batch_op:
        batch_op.drop_column('min_reading_seconds')

    with op.batch_alter_table('attendance_protocols', schema=None) as batch_op:
        batch_op.drop_column('min_reading_seconds')

    op.drop_index('ix_content_reading_logs_content_id', table_name='content_reading_logs')
    op.drop_index('ix_content_reading_logs_user_id', table_name='content_reading_logs')
    op.drop_table('content_reading_logs')
