"""add_onboarding_management_batch

Revision ID: 890999486956
Revises: c738978748e5
Create Date: 2026-04-08 13:55:23.161021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890999486956'
down_revision: Union[str, None] = 'c738978748e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # We use batch_alter_table for SQLite compatibility
    # The columns protocol_id and sop_id might already exist due to a previous partial failure
    # so we focus on ensuring the foreign keys are named and created correctly.
    
    with op.batch_alter_table('onboarding_items', schema=None) as batch_op:
        # Note: If columns were already added, batch_op handles them. 
        # SQLite doesn't support adding constraints to existing columns easily without batch.
        batch_op.create_foreign_key('fk_onboarding_items_sop_id_sops', 'sops', ['sop_id'], ['id'])
        batch_op.create_foreign_key('fk_onboarding_items_protocol_id_attendance_protocols', 'attendance_protocols', ['protocol_id'], ['id'])

    with op.batch_alter_table('user_onboarding_progress', schema=None) as batch_op:
        # If there's an existing unnamed FK, we try to drop it or just let batch handle the state
        # SQLite batch mode often requires recreating the table.
        batch_op.create_foreign_key('fk_user_onboarding_progress_item_id_onboarding_items', 'onboarding_items', ['item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_onboarding_progress', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_onboarding_progress_item_id_onboarding_items', type_='foreignkey')
        batch_op.create_foreign_key(None, 'playlist_sops', ['item_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('onboarding_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_onboarding_items_protocol_id_attendance_protocols', type_='foreignkey')
        batch_op.drop_constraint('fk_onboarding_items_sop_id_sops', type_='foreignkey')

    # ### end Alembic commands ###
